
export const GET_DEFAULT_CITIES = "GET_DEFAULT_CITIES"
export const ADD_CITY = "ADD_CITY"
export const REMOVE_CITY = "REMOVE_CITY"
export const SELECT_DETAIL_CITY = "SELECT_DETAIL_CITY"

export const ADD_FAVORITE = "ADD_FAVORITE"
export const REMOVE_FAVORITE = "REMOVE_FAVORITE"

export const ERROR = "ERROR"
export const RESET_ERROR = "RESET_ERROR"